name       : qt5-speech
version    : 5.12.3
release    : 5
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtspeech-everywhere-src-5.12.3.tar.xz : ed211822765744553fb5abeb97058420668b18a50d985061d949a0e068ee64f5
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt Text-To-Speech library
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(speech-dispatcher)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
