name       : qt5-speech
version    : 5.12.1
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtspeech-everywhere-src-5.12.1.tar.xz : 147524ba6f97c76784beb315ee939614b7a3b4eb1a6417cc0beea662cf0d9121
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt Text-To-Speech library
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(speech-dispatcher)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
