name       : qt5-speech
version    : 5.15.2
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtspeech-everywhere-src-5.15.2.tar.xz : c810fb9eecb08026434422a32e79269627f3bc2941be199e86ec410bdfe883f5
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt Text-To-Speech library
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(speech-dispatcher)
setup      : |
    %qmake CONFIG+=release qtspeech.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
