name       : qt5-speech
version    : 5.13.2
release    : 8
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtspeech-everywhere-src-5.13.2.tar.xz : a0aca08feeac6925ead7f841319bdcfd60bfc126de07807edaf267c2ca8d13d5
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt Text-To-Speech library
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(speech-dispatcher)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
