name       : qt5-speech
version    : 5.15.1
release    : 10
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtspeech-everywhere-src-5.15.1.tar.xz : 7d2a5f7cf653d711de249ce4689959866d2381c625ced7ed4db7c8baaa140edc
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt Text-To-Speech library
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(speech-dispatcher)
setup      : |
    %qmake CONFIG+=release qtspeech.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
