name       : qt5-speech
version    : 5.13.1
release    : 7
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.1/submodules/qtspeech-everywhere-src-5.13.1.tar.xz : 347343a96710b389e8e05506df3c971b9437f101d09677e44f4bf2a87bf25556
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt Text-To-Speech library
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(speech-dispatcher)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
