name       : qt5-speech
version    : 5.13.0
release    : 6
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.0/submodules/qtspeech-everywhere-src-5.13.0.tar.xz : 1bfeea13cc23a9d9a02081f4e3378bc8ef51af5dfd684b261cf0a0e93be5b644
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt Text-To-Speech library
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(speech-dispatcher)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
